import { db } from '@/db';
import { words, courses } from '@/db/schema';
import { sql } from 'drizzle-orm';

async function main() {
    // Check if courses exist
    const existingCourses = await db.select().from(courses);
    
    if (existingCourses.length === 0) {
        console.log('⚠️  No courses found in database. Please run courses seeder first.');
        return;
    }

    const sampleWords = [
        // Course 1 - English Basics (20 words)
        {
            word: 'hello',
            translation: 'hola (Spanish)',
            pronunciation: '/həˈloʊ/',
            example: 'Hello, how are you?',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:00:00').toISOString(),
        },
        {
            word: 'goodbye',
            translation: 'adiós',
            pronunciation: '/ɡʊdˈbaɪ/',
            example: 'Goodbye, see you later!',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:05:00').toISOString(),
        },
        {
            word: 'please',
            translation: 'por favor',
            pronunciation: '/pliːz/',
            example: 'Can I have water, please?',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:10:00').toISOString(),
        },
        {
            word: 'thank you',
            translation: 'gracias',
            pronunciation: '/θæŋk juː/',
            example: 'Thank you for your help.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:15:00').toISOString(),
        },
        {
            word: 'yes',
            translation: 'sí',
            pronunciation: '/jɛs/',
            example: 'Yes, I agree with you.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:20:00').toISOString(),
        },
        {
            word: 'no',
            translation: 'no',
            pronunciation: '/noʊ/',
            example: "No, I don't want that.",
            courseId: 1,
            createdAt: new Date('2024-01-15T10:25:00').toISOString(),
        },
        {
            word: 'water',
            translation: 'agua',
            pronunciation: '/ˈwɔːtər/',
            example: 'I need some water.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
        },
        {
            word: 'food',
            translation: 'comida',
            pronunciation: '/fuːd/',
            example: 'This food is delicious.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:35:00').toISOString(),
        },
        {
            word: 'house',
            translation: 'casa',
            pronunciation: '/haʊs/',
            example: 'I live in a big house.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:40:00').toISOString(),
        },
        {
            word: 'friend',
            translation: 'amigo',
            pronunciation: '/frɛnd/',
            example: 'She is my best friend.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:45:00').toISOString(),
        },
        {
            word: 'family',
            translation: 'familia',
            pronunciation: '/ˈfæməli/',
            example: 'I love my family.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:50:00').toISOString(),
        },
        {
            word: 'work',
            translation: 'trabajo',
            pronunciation: '/wɜːrk/',
            example: 'I work at a hospital.',
            courseId: 1,
            createdAt: new Date('2024-01-15T10:55:00').toISOString(),
        },
        {
            word: 'school',
            translation: 'escuela',
            pronunciation: '/skuːl/',
            example: 'Children go to school.',
            courseId: 1,
            createdAt: new Date('2024-01-15T11:00:00').toISOString(),
        },
        {
            word: 'book',
            translation: 'libro',
            pronunciation: '/bʊk/',
            example: "I'm reading a good book.",
            courseId: 1,
            createdAt: new Date('2024-01-15T11:05:00').toISOString(),
        },
        {
            word: 'car',
            translation: 'carro',
            pronunciation: '/kɑːr/',
            example: "That's a nice car.",
            courseId: 1,
            createdAt: new Date('2024-01-15T11:10:00').toISOString(),
        },
        {
            word: 'money',
            translation: 'dinero',
            pronunciation: '/ˈmʌni/',
            example: 'I need to save money.',
            courseId: 1,
            createdAt: new Date('2024-01-15T11:15:00').toISOString(),
        },
        {
            word: 'time',
            translation: 'tiempo',
            pronunciation: '/taɪm/',
            example: 'What time is it?',
            courseId: 1,
            createdAt: new Date('2024-01-15T11:20:00').toISOString(),
        },
        {
            word: 'happy',
            translation: 'feliz',
            pronunciation: '/ˈhæpi/',
            example: 'I feel very happy today.',
            courseId: 1,
            createdAt: new Date('2024-01-15T11:25:00').toISOString(),
        },
        {
            word: 'good',
            translation: 'bueno',
            pronunciation: '/ɡʊd/',
            example: "That's a good idea.",
            courseId: 1,
            createdAt: new Date('2024-01-15T11:30:00').toISOString(),
        },
        {
            word: 'love',
            translation: 'amor',
            pronunciation: '/lʌv/',
            example: 'I love learning English.',
            courseId: 1,
            createdAt: new Date('2024-01-15T11:35:00').toISOString(),
        },

        // Course 2 - Travel Spanish (20 words)
        {
            word: 'hola',
            translation: 'hello',
            pronunciation: '/ˈola/',
            example: '¡Hola! ¿Cómo estás?',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:00:00').toISOString(),
        },
        {
            word: 'adiós',
            translation: 'goodbye',
            pronunciation: '/aˈðjos/',
            example: 'Adiós, hasta luego.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:05:00').toISOString(),
        },
        {
            word: 'gracias',
            translation: 'thank you',
            pronunciation: '/ˈɡɾasjas/',
            example: 'Gracias por tu ayuda.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:10:00').toISOString(),
        },
        {
            word: 'por favor',
            translation: 'please',
            pronunciation: '/poɾ faˈβoɾ/',
            example: 'Una cerveza, por favor.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:15:00').toISOString(),
        },
        {
            word: 'sí',
            translation: 'yes',
            pronunciation: '/si/',
            example: 'Sí, quiero ir.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:20:00').toISOString(),
        },
        {
            word: 'no',
            translation: 'no',
            pronunciation: '/no/',
            example: 'No, gracias.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:25:00').toISOString(),
        },
        {
            word: 'aeropuerto',
            translation: 'airport',
            pronunciation: '/aeɾoˈpweɾto/',
            example: '¿Dónde está el aeropuerto?',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:30:00').toISOString(),
        },
        {
            word: 'hotel',
            translation: 'hotel',
            pronunciation: '/oˈtel/',
            example: 'Necesito un hotel.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:35:00').toISOString(),
        },
        {
            word: 'restaurante',
            translation: 'restaurant',
            pronunciation: '/restaurˈante/',
            example: '¿Hay un restaurante cerca?',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:40:00').toISOString(),
        },
        {
            word: 'taxi',
            translation: 'taxi',
            pronunciation: '/ˈtaksi/',
            example: 'Necesito un taxi.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:45:00').toISOString(),
        },
        {
            word: 'playa',
            translation: 'beach',
            pronunciation: '/ˈplaʝa/',
            example: 'Vamos a la playa.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:50:00').toISOString(),
        },
        {
            word: 'museo',
            translation: 'museum',
            pronunciation: '/muˈseo/',
            example: 'El museo está cerrado.',
            courseId: 2,
            createdAt: new Date('2024-01-16T10:55:00').toISOString(),
        },
        {
            word: 'precio',
            translation: 'price',
            pronunciation: '/ˈpɾesjo/',
            example: '¿Cuál es el precio?',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:00:00').toISOString(),
        },
        {
            word: 'cuánto cuesta',
            translation: 'how much',
            pronunciation: '/ˈkwanto ˈkwesta/',
            example: '¿Cuánto cuesta esto?',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:05:00').toISOString(),
        },
        {
            word: 'habitación',
            translation: 'room',
            pronunciation: '/aβitaˈsjon/',
            example: 'Quiero una habitación.',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:10:00').toISOString(),
        },
        {
            word: 'ayuda',
            translation: 'help',
            pronunciation: '/aˈʝuða/',
            example: 'Necesito ayuda.',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:15:00').toISOString(),
        },
        {
            word: 'baño',
            translation: 'bathroom',
            pronunciation: '/ˈbaɲo/',
            example: '¿Dónde está el baño?',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:20:00').toISOString(),
        },
        {
            word: 'comida',
            translation: 'food',
            pronunciation: '/koˈmiða/',
            example: 'La comida es deliciosa.',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:25:00').toISOString(),
        },
        {
            word: 'agua',
            translation: 'water',
            pronunciation: '/ˈaɣwa/',
            example: 'Quiero agua, por favor.',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:30:00').toISOString(),
        },
        {
            word: 'mapa',
            translation: 'map',
            pronunciation: '/ˈmapa/',
            example: '¿Tienes un mapa?',
            courseId: 2,
            createdAt: new Date('2024-01-16T11:35:00').toISOString(),
        },

        // Course 3 - Business French (18 words)
        {
            word: 'réunion',
            translation: 'meeting',
            pronunciation: '/ʁeynjɔ̃/',
            example: 'La réunion commence à 9h.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:00:00').toISOString(),
        },
        {
            word: 'contrat',
            translation: 'contract',
            pronunciation: '/kɔ̃tʁa/',
            example: "Signez le contrat, s'il vous plaît.",
            courseId: 3,
            createdAt: new Date('2024-01-17T10:05:00').toISOString(),
        },
        {
            word: 'client',
            translation: 'client',
            pronunciation: '/klijɑ̃/',
            example: 'Le client est satisfait.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:10:00').toISOString(),
        },
        {
            word: 'entreprise',
            translation: 'company',
            pronunciation: '/ɑ̃tʁəpʁiz/',
            example: 'Notre entreprise grandit rapidement.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:15:00').toISOString(),
        },
        {
            word: 'budget',
            translation: 'budget',
            pronunciation: '/bydʒɛ/',
            example: 'Quel est votre budget?',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:20:00').toISOString(),
        },
        {
            word: 'projet',
            translation: 'project',
            pronunciation: '/pʁɔʒɛ/',
            example: 'Le projet avance bien.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:25:00').toISOString(),
        },
        {
            word: 'équipe',
            translation: 'team',
            pronunciation: '/ekip/',
            example: 'Notre équipe est excellente.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:30:00').toISOString(),
        },
        {
            word: 'directeur',
            translation: 'director',
            pronunciation: '/diʁɛktœʁ/',
            example: 'Le directeur arrive bientôt.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:35:00').toISOString(),
        },
        {
            word: 'bureau',
            translation: 'office',
            pronunciation: '/byʁo/',
            example: 'Mon bureau est au troisième étage.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:40:00').toISOString(),
        },
        {
            word: 'emploi',
            translation: 'job',
            pronunciation: '/ɑ̃plwa/',
            example: 'Je cherche un emploi.',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:45:00').toISOString(),
        },
        {
            word: 'salaire',
            translation: 'salary',
            pronunciation: '/salɛʁ/',
            example: 'Quel est le salaire proposé?',
            courseId: 3,
            createdAt: new Date('2024-01-17T10:50:00').toISOString(),
        },
        {
            word: 'rendez-vous',
            translation: 'appointment',
            pronunciation: '/ʁɑ̃devu/',
            example: "J'ai un rendez-vous à 14h.",
            courseId: 3,
            createdAt: new Date('2024-01-17T10:55:00').toISOString(),
        },
        {
            word: 'présentation',
            translation: 'presentation',
            pronunciation: '/pʁezɑ̃tasjɔ̃/',
            example: 'La présentation est prête.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:00:00').toISOString(),
        },
        {
            word: 'négociation',
            translation: 'negotiation',
            pronunciation: '/neɡɔsjasjɔ̃/',
            example: 'La négociation est difficile.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:05:00').toISOString(),
        },
        {
            word: 'marché',
            translation: 'market',
            pronunciation: '/maʁʃe/',
            example: 'Le marché est en croissance.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:10:00').toISOString(),
        },
        {
            word: 'vente',
            translation: 'sale',
            pronunciation: '/vɑ̃t/',
            example: 'Les ventes augmentent.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:15:00').toISOString(),
        },
        {
            word: 'rapport',
            translation: 'report',
            pronunciation: '/ʁapɔʁ/',
            example: 'Le rapport est terminé.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:20:00').toISOString(),
        },
        {
            word: 'objectif',
            translation: 'objective',
            pronunciation: '/ɔbʒɛktif/',
            example: 'Nous avons atteint notre objectif.',
            courseId: 3,
            createdAt: new Date('2024-01-17T11:25:00').toISOString(),
        },

        // Course 4 - Japanese for Beginners (17 words)
        {
            word: 'こんにちは',
            translation: 'hello',
            pronunciation: '/konnichiwa/',
            example: 'こんにちは！元気ですか？',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:00:00').toISOString(),
        },
        {
            word: 'ありがとう',
            translation: 'thank you',
            pronunciation: '/arigatou/',
            example: 'ありがとうございます。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:05:00').toISOString(),
        },
        {
            word: 'さようなら',
            translation: 'goodbye',
            pronunciation: '/sayounara/',
            example: 'さようなら、また明日。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:10:00').toISOString(),
        },
        {
            word: 'はい',
            translation: 'yes',
            pronunciation: '/hai/',
            example: 'はい、わかりました。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:15:00').toISOString(),
        },
        {
            word: 'いいえ',
            translation: 'no',
            pronunciation: '/iie/',
            example: 'いいえ、違います。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:20:00').toISOString(),
        },
        {
            word: 'すみません',
            translation: 'excuse me',
            pronunciation: '/sumimasen/',
            example: 'すみません、お願いします。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:25:00').toISOString(),
        },
        {
            word: 'おはよう',
            translation: 'good morning',
            pronunciation: '/ohayou/',
            example: 'おはようございます。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:30:00').toISOString(),
        },
        {
            word: 'おやすみ',
            translation: 'good night',
            pronunciation: '/oyasumi/',
            example: 'おやすみなさい。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:35:00').toISOString(),
        },
        {
            word: '水 (みず)',
            translation: 'water',
            pronunciation: '/mizu/',
            example: '水をください。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:40:00').toISOString(),
        },
        {
            word: '食べ物 (たべもの)',
            translation: 'food',
            pronunciation: '/tabemono/',
            example: 'この食べ物は美味しいです。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:45:00').toISOString(),
        },
        {
            word: '学校 (がっこう)',
            translation: 'school',
            pronunciation: '/gakkou/',
            example: '私は学校に行きます。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:50:00').toISOString(),
        },
        {
            word: '仕事 (しごと)',
            translation: 'work',
            pronunciation: '/shigoto/',
            example: '今日は仕事があります。',
            courseId: 4,
            createdAt: new Date('2024-01-18T10:55:00').toISOString(),
        },
        {
            word: '友達 (ともだち)',
            translation: 'friend',
            pronunciation: '/tomodachi/',
            example: '彼は私の友達です。',
            courseId: 4,
            createdAt: new Date('2024-01-18T11:00:00').toISOString(),
        },
        {
            word: '家 (いえ)',
            translation: 'house',
            pronunciation: '/ie/',
            example: '私の家は小さいです。',
            courseId: 4,
            createdAt: new Date('2024-01-18T11:05:00').toISOString(),
        },
        {
            word: '本 (ほん)',
            translation: 'book',
            pronunciation: '/hon/',
            example: 'この本は面白いです。',
            courseId: 4,
            createdAt: new Date('2024-01-18T11:10:00').toISOString(),
        },
        {
            word: '車 (くるま)',
            translation: 'car',
            pronunciation: '/kuruma/',
            example: '新しい車が欲しいです。',
            courseId: 4,
            createdAt: new Date('2024-01-18T11:15:00').toISOString(),
        },
        {
            word: '時間 (じかん)',
            translation: 'time',
            pronunciation: '/jikan/',
            example: '時間がありません。',
            courseId: 4,
            createdAt: new Date('2024-01-18T11:20:00').toISOString(),
        },
    ];

    await db.insert(words).values(sampleWords);
    
    console.log(`✅ Words seeder completed successfully - ${sampleWords.length} words inserted`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});